from typing import Protocol
from apps.api.app.features.interactions.schemas import InteractionEvent
from apps.api.app.features.memory.schemas import StudentMemory
from .schemas import LessonRecord,StudentProfile
class StudentRepository(Protocol):
    def save_profile(self,profile:StudentProfile)->None:...
    def get_profile(self,uid:str)->StudentProfile|None:...
    def save_lesson(self,lesson:LessonRecord)->None:...
    def lessons(self,uid:str,limit:int=50)->list[LessonRecord]:...
    def save_event(self,uid:str,event:InteractionEvent)->None:...
    def save_attempt(self,uid:str,event:InteractionEvent,practice_id:str)->None:...
    def get_memory(self,uid:str)->StudentMemory:...
    def save_memory(self,memory:StudentMemory)->None:...
    def reset_memory(self,uid:str)->None:...
class InMemoryStudentRepository:
    def __init__(self):self.profiles={};self.lesson_items={};self.events={};self.attempts={};self.memories={}
    def save_profile(self,p):self.profiles[p.student_id]=p
    def get_profile(self,uid):return self.profiles.get(uid)
    def save_lesson(self,x):self.lesson_items[x.lesson_id]=x
    def lessons(self,uid,limit=50):return sorted([x for x in self.lesson_items.values() if x.student_id==uid],key=lambda x:x.created_at,reverse=True)[:limit]
    def save_event(self,uid,event):self.events[event.event_id]=(uid,event)
    def save_attempt(self,uid,event,practice_id):self.attempts[event.event_id]={"uid":uid,"event":event,"practice_id":practice_id}
    def get_memory(self,uid):return self.memories.get(uid) or StudentMemory(student_id=uid)
    def save_memory(self,memory):self.memories[memory.student_id]=memory
    def reset_memory(self,uid):self.memories.pop(uid,None)
