from typing import Protocol
from .schemas import StudentMemory
class MemoryRepository(Protocol):
    def get(self,uid:str)->StudentMemory:...
    def save(self,memory:StudentMemory)->None:...
    def delete(self,uid:str)->None:...
