'use client';
import {ClipboardEvent,useEffect,useRef,useState} from 'react';
import {analyzeQuestionImage,VisionAnalysis,VisionApiError} from '../lib/vision-api';
import {generateLesson,GeneratedLesson,LessonApiError} from '../lib/lesson-api';
import {InteractionPanel} from './InteractionPanel';
import {AnalysisLoading} from './AnalysisLoading';import {ErrorBanner} from './ErrorBanner';import {ImagePreview} from './ImagePreview';import {UploadCard} from './UploadCard';import {TeacherBoard} from './TeacherBoard';import {LessonText} from './LessonText';
type State='idle'|'image_selected'|'uploading'|'analyzing'|'planning'|'verifying'|'rendering'|'success'|'error';
const TYPES=['image/jpeg','image/png','image/webp'],MAX=10*1024*1024;
const ERRORS:Record<string,string>={image_required:'Lütfen bir soru görseli seçin.',unsupported_image_type:'Yalnızca JPG, PNG veya WEBP kullanın.',image_too_large:'Görsel 10 MB sınırını aşıyor.',invalid_image:'Görsel okunamadı.',provider_not_configured:'AI servisi yapılandırılmamış.',provider_unavailable:'AI servisine şu anda ulaşılamıyor.',lesson_provider_not_configured:'Öğretmen anlatımı servisi yapılandırılmamış.',lesson_provider_unavailable:'Anlatım şu anda oluşturulamadı.',verification_contradiction:'Bu çözüm matematiksel kontrolden geçemedi. Yeniden inceleyelim.',lesson_timeout:'İşlem zaman aşımına uğradı.',network_error:'TeacherAI sunucusuna ulaşılamıyor.',lesson_error:'Çözüm oluşturulamadı.'};
export function SolveWorkspace(){const[state,setState]=useState<State>('idle'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[analysis,setAnalysis]=useState<VisionAnalysis|null>(null),[result,setResult]=useState<GeneratedLesson|null>(null),[error,setError]=useState(''),[dragging,setDragging]=useState(false),[showText,setShowText]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const busy=['uploading','analyzing','planning','verifying','rendering'].includes(state);
useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
function select(selected:File){if(!TYPES.includes(selected.type)){setError(ERRORS.unsupported_image_type);setState('error');return}if(selected.size>MAX){setError(ERRORS.image_too_large);setState('error');return}if(preview)URL.revokeObjectURL(preview);setFile(selected);setPreview(URL.createObjectURL(selected));setAnalysis(null);setResult(null);setError('');setState('image_selected')}
function reset(){if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview('');setAnalysis(null);setResult(null);setError('');setState('idle')}
async function createLesson(value:VisionAnalysis){setState('planning');try{const generated=await generateLesson(value);setState('rendering');setResult(generated);setState('success')}catch(e){const code=e instanceof LessonApiError?e.code:'lesson_error';setError(ERRORS[code]??ERRORS.lesson_error);setState('error')}}
async function solve(){if(!file)return;setError('');setResult(null);setState('uploading');try{const value=await analyzeQuestionImage(file,()=>setState('analyzing'));setAnalysis(value);await createLesson(value)}catch(e){const code=e instanceof VisionApiError?e.code:'network_error';setError(ERRORS[code]??ERRORS.network_error);setState('error')}}
function paste(e:ClipboardEvent<HTMLElement>){const image=Array.from(e.clipboardData.files).find(x=>x.type.startsWith('image/'));if(image&&!busy){e.preventDefault();select(image)}}
return <div className="solvePage" onPaste={paste}><header className="solveIntro"><p className="eyebrow">TeacherAI • MathAI</p><h1>Sorunu yükle,<br/><span>tahtada birlikte çözelim.</span></h1><p>Soruyu okur, öğretmen anlatımını hazırlar ve desteklenen matematiği bağımsız olarak kontrol eder.</p></header><div className="solveGrid"><section className="solveInput">{!file?<UploadCard inputRef={inputRef} disabled={busy} dragging={dragging} onDraggingChange={setDragging} onFile={select}/>:<ImagePreview file={file} previewUrl={preview} disabled={busy} onRemove={reset} onReplace={()=>inputRef.current?.click()}/>} {file&&<input ref={inputRef} className="visuallyHidden" type="file" accept={TYPES.join(',')} capture="environment" aria-label="Görseli değiştir" onChange={e=>{const f=e.target.files?.[0];if(f)select(f);e.target.value=''}}/>}{error&&<ErrorBanner message={error}/>} {error&&analysis&&!result&&<button className="secondaryButton retryButton" onClick={()=>createLesson(analysis)}>Yeniden incele</button>}<div className="solveActions"><button className="primaryButton analyzeButton" onClick={solve} disabled={!file||busy}>Soruyu Çöz</button><button className="secondaryButton" onClick={reset} disabled={!file||busy}>Temizle</button></div><p className="privacyNote">Görsel işlemden sonra geçici depolamadan silinir.</p></section><aside className="solveOutput">{busy&&<AnalysisLoading uploading={state==='uploading'} stage={state}/>} {!busy&&!result&&!error&&<div className="resultEmpty"><span>✦</span><h2>Teacher Board burada açılacak</h2><p>Kurallar, adımlar, öğretmen işaretleri ve kontrol edilmiş sonuç tek tahtada.</p></div>}{result&&<><TeacherBoard result={result}/><InteractionPanel lesson={result.lesson}/><button className="textToggle" onClick={()=>setShowText(!showText)} aria-expanded={showText}>{showText?'Metin anlatımını gizle':'Metin olarak göster'}</button>{showText&&<LessonText lesson={result.lesson}/>} {process.env.NEXT_PUBLIC_TEACHERAI_DEBUG==='true'&&<details className="technicalDetails"><summary>Teknik detaylar</summary><pre>{JSON.stringify(result,null,2)}</pre></details>}</>}</aside></div></div>}
