import {ChangeEvent,DragEvent,KeyboardEvent,RefObject,useRef} from 'react';
interface Props{inputRef:RefObject<HTMLInputElement|null>;disabled:boolean;dragging:boolean;onDraggingChange:(value:boolean)=>void;onFile:(file:File)=>void}
export function UploadCard({inputRef,disabled,dragging,onDraggingChange,onFile}:Props){const cameraRef=useRef<HTMLInputElement>(null),galleryRef=useRef<HTMLInputElement>(null);const changed=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)onFile(file);event.target.value=''};const dropped=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();onDraggingChange(false);const file=event.dataTransfer.files[0];if(file&&!disabled)onFile(file)};const openFile=()=>!disabled&&inputRef.current?.click();const keyed=(event:KeyboardEvent<HTMLDivElement>)=>{if(event.target!==event.currentTarget)return;if(event.key==='Enter'||event.key===' '){event.preventDefault();openFile()}};return <div className={`uploadCard ${dragging?'dragging':''}`} role="button" tabIndex={disabled?-1:0} aria-label="Soru fotoğrafını sürükle veya dosya seç" aria-disabled={disabled} onClick={openFile} onKeyDown={keyed} onDragEnter={e=>{e.preventDefault();onDraggingChange(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>onDraggingChange(false)} onDrop={dropped}>
<input ref={cameraRef} className="visuallyHidden" type="file" accept="image/*" capture="environment" onChange={changed} disabled={disabled} aria-label="Arka kamerayla soru fotoğrafı çek"/>
<input ref={galleryRef} className="visuallyHidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={changed} disabled={disabled} aria-label="Galeriden soru görseli seç"/>
<input ref={inputRef} className="visuallyHidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={changed} disabled={disabled} aria-label="Bilgisayardan soru görseli yükle"/>
<span className="uploadGlyph" aria-hidden="true">＋</span><h2>Soru fotoğrafını ekle</h2><p className="desktopUploadText">Fotoğrafı buraya sürükle veya aşağıdan bir yöntem seç. Görseli <strong>Ctrl+V / Cmd+V</strong> ile de yapıştırabilirsin.</p>
<div className="uploadChoices"><button type="button" className="cameraChoice" onClick={e=>{e.stopPropagation();cameraRef.current?.click()}} disabled={disabled}><span aria-hidden="true">📷</span>Kamerayla Çek</button><button type="button" onClick={e=>{e.stopPropagation();galleryRef.current?.click()}} disabled={disabled}><span aria-hidden="true">🖼️</span>Galeriden Seç</button><button type="button" className="fileChoice" onClick={e=>{e.stopPropagation();inputRef.current?.click()}} disabled={disabled}><span aria-hidden="true">↥</span>Dosya Yükle</button></div>
<p className="uploadGuidance">En iyi sonuç için sorunun tamamı ve varsa şekil veya grafik net görünsün.</p><span className="formatNote">JPG, PNG, WEBP · En fazla 10 MB</span></div>}
